import type { AppCardDto } from "@altstore/types";

export const MOCK_APPS: AppCardDto[] = [
  {
    id: "1",
    slug: "opentrack",
    name: "OpenTrack",
    category: "PRODUCTIVITY",
    iconUrl: "",
    shortDesc: "Track your daily habits and build streaks with a clean, minimal interface.",
    platform: "ANDROID",
    latestVersion: "3.2.1",
    latestFileSize: "18.4 MB",
    totalDownloads: 84200,
  },
  {
    id: "2",
    slug: "vaultpass",
    name: "VaultPass",
    category: "TOOLS",
    iconUrl: "",
    shortDesc: "Open source password manager with end-to-end encryption and offline mode.",
    platform: "ANDROID",
    latestVersion: "2.0.0",
    latestFileSize: "12.1 MB",
    totalDownloads: 210400,
  },
  {
    id: "3",
    slug: "tunefree",
    name: "TuneFree",
    category: "ENTERTAINMENT",
    iconUrl: "",
    shortDesc: "Stream ad-free music from libre sources. No account required.",
    platform: "ANDROID",
    latestVersion: "1.4.5",
    latestFileSize: "31.7 MB",
    totalDownloads: 63000,
  },
  {
    id: "4",
    slug: "mapwise",
    name: "MapWise",
    category: "NAVIGATION",
    iconUrl: "",
    shortDesc: "Offline maps powered by OpenStreetMap. Navigate without a data connection.",
    platform: "ANDROID",
    latestVersion: "5.1.0",
    latestFileSize: "54.9 MB",
    totalDownloads: 390000,
  },
  {
    id: "5",
    slug: "notepilot",
    name: "NotePilot",
    category: "PRODUCTIVITY",
    iconUrl: "",
    shortDesc: "Markdown-first note taking with sync across devices. Privacy-first.",
    platform: "BOTH",
    latestVersion: "4.0.2",
    latestFileSize: "22.6 MB",
    totalDownloads: 150000,
  },
  {
    id: "6",
    slug: "lexify",
    name: "Lexify",
    category: "EDUCATION",
    iconUrl: "",
    shortDesc: "Learn new languages with spaced repetition and AI-generated sentences.",
    platform: "ANDROID",
    latestVersion: "2.3.0",
    latestFileSize: "27.3 MB",
    totalDownloads: 91000,
  },
  {
    id: "7",
    slug: "pixelshift",
    name: "PixelShift",
    category: "PHOTOGRAPHY",
    iconUrl: "",
    shortDesc: "Non-destructive photo editing with RAW support. No subscription.",
    platform: "ANDROID",
    latestVersion: "1.9.1",
    latestFileSize: "41.0 MB",
    totalDownloads: 47000,
  },
  {
    id: "8",
    slug: "budgetly",
    name: "Budgetly",
    category: "FINANCE",
    iconUrl: "",
    shortDesc: "Personal finance tracker with zero cloud dependency. All data stays on device.",
    platform: "ANDROID",
    latestVersion: "3.5.0",
    latestFileSize: "9.8 MB",
    totalDownloads: 72000,
  },
];
